export const PATHWAY_THRESHOLDS = {
  DNA_WINDOW_DAYS: 28,
  STAGNANT_DAYS: 30,
  STAGNANT_DAYS_HIGH: 60,
  GHOST_ACTIVITY_DAYS: 60,
  GHOST_WAITING_DAYS: 200,
  VALIDATION_OVERDUE_DAYS: 42,
} as const;
