import { Pathway } from "./schema";

export const pathwayFixtures: Pathway[] = [
  {
    pathway_id: "pth-001",
    patient_id: "nhs-7731052",
    patient_name: "Sandra Livingstone",
    patient_age: 62,
    specialty: "Orthopaedics",
    consultant: "Dr Patel",
    site: "Royal Infirmary",
    priority: "urgent",
    stage: "triage",
    rtt_status: "at_risk",
    waiting_days: 142,
    last_activity_date: "2026-02-18",
    owner_id: "u-ops-1",
    validation_status: "required",
    dna_count: 0,
    clock_status: "running",
    breach_flag: false,
    breach_root_cause: null,
    decision_to_treat_date: "2025-10-01",
    scheduled_date: null,
    procedure: "Hip Hemiarthroplasty",
    opcs_code: "W37.1",
    duration: "90m",
    rtt_target: "18 weeks",
  },
  {
    pathway_id: "pth-002",
    patient_id: "nhs-4821093",
    patient_name: "Margaret O'Brien",
    patient_age: 67,
    specialty: "Cardiology",
    consultant: "Dr Green",
    site: "City Hospital",
    priority: "routine",
    stage: "diagnostics",
    rtt_status: "breaching",
    waiting_days: 278,
    last_activity_date: "2026-01-10",
    owner_id: null,
    validation_status: "overdue",
    dna_count: 1,
    clock_status: "running",
    breach_flag: true,
    breach_root_cause: "diagnostics",
    decision_to_treat_date: "2025-05-02",
    scheduled_date: null,
    procedure: "CABG Workup",
    opcs_code: "K50.1",
    duration: "60m",
    rtt_target: "52 weeks",
  },
  {
    pathway_id: "pth-003",
    patient_id: "nhs-6622017",
    patient_name: "Yasmin Hassan",
    patient_age: 44,
    specialty: "ENT",
    consultant: "Dr Miles",
    site: "Royal Infirmary",
    priority: "soon",
    stage: "decision",
    rtt_status: "on_track",
    waiting_days: 48,
    last_activity_date: "2026-02-20",
    owner_id: "u-ops-2",
    validation_status: "validated",
    dna_count: 0,
    clock_status: "running",
    breach_flag: false,
    breach_root_cause: null,
    decision_to_treat_date: "2026-01-14",
    scheduled_date: "2026-03-02",
    procedure: "Mastoid Procedure",
    opcs_code: "F16.3",
    duration: "45m",
    rtt_target: "18 weeks",
  },
  {
    pathway_id: "pth-004",
    patient_id: "nhs-1102934",
    patient_name: "Marcus Osei",
    patient_age: 59,
    specialty: "General Surgery",
    consultant: "Dr Shah",
    site: "City Hospital",
    priority: "urgent",
    stage: "scheduled",
    rtt_status: "within_52_week",
    waiting_days: 320,
    last_activity_date: "2026-02-05",
    owner_id: "u-ops-3",
    validation_status: "validated",
    dna_count: 2,
    clock_status: "running",
    breach_flag: true,
    breach_root_cause: "capacity",
    decision_to_treat_date: "2025-03-22",
    scheduled_date: "2026-02-28",
    procedure: "Anterior Resection",
    opcs_code: "T85.2",
    duration: "120m",
    rtt_target: "52 weeks",
  },
  {
    pathway_id: "pth-005",
    patient_id: "nhs-3310447",
    patient_name: "David Okafor",
    patient_age: 54,
    specialty: "Orthopaedics",
    consultant: "Dr Patel",
    site: "Royal Infirmary",
    priority: "routine",
    stage: "referral",
    rtt_status: "on_track",
    waiting_days: 18,
    last_activity_date: "2026-02-21",
    owner_id: null,
    validation_status: "never_validated",
    dna_count: 0,
    clock_status: "running",
    breach_flag: false,
    breach_root_cause: null,
    decision_to_treat_date: null,
    scheduled_date: null,
    procedure: null,
    opcs_code: null,
    duration: null,
    rtt_target: "18 weeks",
  },
  {
    pathway_id: "pth-006",
    patient_id: "nhs-6640281",
    patient_name: "Fiona Clarke",
    patient_age: 43,
    specialty: "Neurology",
    consultant: "Dr Adams",
    site: "Central Clinic",
    priority: "soon",
    stage: "triage",
    rtt_status: "at_risk",
    waiting_days: 95,
    last_activity_date: "2026-01-02",
    owner_id: "u-ops-4",
    validation_status: "required",
    dna_count: 0,
    clock_status: "running",
    breach_flag: false,
    breach_root_cause: null,
    decision_to_treat_date: "2025-12-04",
    scheduled_date: null,
    procedure: "Nerve Conduction",
    opcs_code: "A12.4",
    duration: "30m",
    rtt_target: "18 weeks",
  },
  {
    pathway_id: "pth-007",
    patient_id: "nhs-5510982",
    patient_name: "Chioma Eze",
    patient_age: 31,
    specialty: "Cardiology",
    consultant: "Dr Green",
    site: "City Hospital",
    priority: "routine",
    stage: "diagnostics",
    rtt_status: "at_risk",
    waiting_days: 132,
    last_activity_date: "2025-12-18",
    owner_id: "u-ops-5",
    validation_status: "overdue",
    dna_count: 1,
    clock_status: "running",
    breach_flag: false,
    breach_root_cause: null,
    decision_to_treat_date: "2025-09-18",
    scheduled_date: null,
    procedure: "Echocardiogram",
    opcs_code: "K01.9",
    duration: "60m",
    rtt_target: "18 weeks",
  },
];
