export const RICH_VARIANTS = {
  section_overview_intro: [
    "Sure - here is what {{section}} covers, and what we can open next.",
    "Absolutely. {{section}} is where you will find these key pages.",
    "Got it. Here is a quick tour of {{section}} and the main views.",
    "No problem - {{section}} has a few core pages worth starting with.",
    "Alright - here are the most useful {{section}} views to jump into.",
    "Yep. I can walk you through {{section}}. Here is the menu.",
    "Understood - let us orient you in {{section}} first.",
    "Makes sense. Here is the layout of {{section}} in plain terms.",
    "Okay - {{section}} is organised around these views.",
    "Happy to. Here is what lives inside {{section}}.",
    "Let us do it - {{section}} has these pages ready to use.",
    "Cool. Here are the {{section}} pages I can open or summarise.",
    "Right - if we start in {{section}}, these are the best entry points.",
    "Here is the simplest way to think about {{section}}: these views.",
    "Good call. {{section}} is basically these pages and workflows.",
    "Got you. {{section}} breaks down into these main areas.",
    "Alright - here is what {{section}} contains and where to go next.",
    "If you are exploring {{section}}, start with one of these views.",
    "Here is a clear overview of {{section}} and your next clicks.",
    "Easy. {{section}} equals these views. Pick one and I will take you there.",
  ],
  section_overview_summary: [
    "Top views I can help with: {{views}}.",
    "The main pages in {{section}} are: {{views}}.",
    "Most people start with: {{views}}.",
    "Your quickest starting points are: {{views}}.",
    "If you are not sure where to begin, try: {{views}}.",
    "Here are the core views available: {{views}}.",
    "These are the most relevant pages right now: {{views}}.",
    "Here is what is available in {{section}} today: {{views}}.",
    "The practical {{section}} views to open are: {{views}}.",
    "You have got a few solid options: {{views}}.",
    "The best first clicks in {{section}} are: {{views}}.",
    "Here are the most useful screens in {{section}}: {{views}}.",
    "If you tell me what you are trying to achieve, I will pick from: {{views}}.",
    "We can go straight to a view - your options include: {{views}}.",
    "These pages are ready for you to open: {{views}}.",
    "Here is the short list of what matters in {{section}}: {{views}}.",
    "This is the menu of views I can read or open: {{views}}.",
    "Here are the pages I can summarise right away: {{views}}.",
    "Pick one of these and I will guide you through it: {{views}}.",
    "If you want, I can open one of these now: {{views}}.",
  ],
  explore_intro: [
    "Yep - I can show you what is available. I will start with a couple of useful views.",
    "Sure. I will pull up a quick snapshot from the most relevant pages.",
    "Got it - I will start by checking a couple of high-signal views.",
    "No worries. I will pick a good starting point and show you what I find.",
    "Alright - I will explore what is wired up and surface the most useful bits.",
    "Okay - I will grab a quick overview from the pages I can read right now.",
    "Understood. I will start with a broad view, then we can zoom in.",
    "Cool - I will start somewhere sensible and give you options from there.",
    "Makes sense. I will take a quick look and suggest the best next step.",
    "Sounds good. I will pull a small sample from the most relevant page(s).",
    "Sure thing - I will show you a quick what-is-here tour using the pages I can read.",
    "Alright - I will fetch a snapshot and we will decide where to go next.",
    "Okay - I will start with the most actionable views and summarise them.",
    "Got you. I will pull up what is available and give you a clean menu.",
    "No problem - I will read a couple of pages and suggest the best follow-ups.",
    "Let us do that. I will start with what is most likely to help right now.",
    "Good plan - I will surface the highest-value pages first.",
    "Yep. I will check a couple of pages and then you can steer me.",
    "Alright - I will do a quick scan and show you what I can act on.",
    "Sure - I will start with the pages that usually answer questions fastest.",
  ],
  view_summary_intro: [
    "Here is what I see on {{view}}.",
    "Alright - here is the gist of {{view}}.",
    "Got it. This is what {{view}} is showing.",
    "Okay - I have pulled {{view}}. Here is the summary.",
    "Understood - here is a quick read of {{view}}.",
    "Here is the current picture from {{view}}.",
    "I am looking at {{view}} now - here is what stands out.",
    "Here is the clean summary of {{view}}.",
    "Pulled {{view}} - here is what matters.",
    "Here is what is available from {{view}}.",
    "On {{view}}, the key points are:",
    "Here is the headline view from {{view}}.",
    "Here is a straightforward summary of {{view}}.",
    "Here is what {{view}} contains at a glance.",
    "Here is the useful part of {{view}} without fluff.",
    "Let us keep it simple - {{view}} is showing:",
    "From {{view}}, here are the key takeaways.",
    "I have read {{view}} - here is the short version.",
    "Quick scan of {{view}}: here is what I found.",
    "Here is the practical summary of {{view}} you can act on.",
  ],
  clarify_wrappers: [
    "Quick check so I do not take you down the wrong path: {{question}}",
    "Just to make sure I am aiming at the right thing: {{question}}",
    "Before I proceed, one small detail: {{question}}",
    "So I can do this properly, tell me: {{question}}",
    "One clarification and then I will move: {{question}}",
    "To keep this tight and useful: {{question}}",
    "Sanity check before I pull anything: {{question}}",
    "Help me narrow it slightly: {{question}}",
    "To avoid guessing, I need one choice: {{question}}",
    "Pick one and I will run with it: {{question}}",
    "One quick decision point: {{question}}",
    "So I can prioritise correctly: {{question}}",
    "To get you the right answer first time: {{question}}",
    "I can do that - first, {{question}}",
    "Before I summarise, {{question}}",
    "To keep it accurate and on-target: {{question}}",
    "Tiny question, then I will proceed: {{question}}",
    "Which direction do you want me to take? {{question}}",
    "I can help - I just need this: {{question}}",
    "To make this actionable: {{question}}",
  ],
} as const;
